#!/bin/sh

if [ "$1" = "-2.0" ]; then
	shift
	python3 ~/timez.py -2.0 $*
else
	python3 ~/timez.py $*
fi
exit 0

# PID=$!
# sleep 1

if [ -e /proc/$PID ]; then
	info=`wmctrl -p -G -l | awk "/$PID/ {print}"`
	if [ "$info" ]; then
		wid=`echo $info | awk '{print $1}'`
		wmctrl -i -r $wid -b add,above
#		wmctrl -i -r $wid -b add,skip_taskbar
#		wmctrl -i -r $wid -b add,skip_pager
		exit 0
	fi
fi
exit 1
